2023-07-07 17:24:57.691 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration colorfulclouds which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-07 17:24:57.692 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration ics_calendar which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-07 17:24:57.693 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration xiaomi_miot_raw which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-07 17:24:57.694 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-07-07 17:25:00.273 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing component homeassistant.components.cloud
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/homeassistant/components/cloud/__init__.py", line 35, in <module>
    from . import account_link, http_api
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/homeassistant/components/cloud/http_api.py", line 20, in <module>
    from homeassistant.components import assist_pipeline, conversation, websocket_api
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/homeassistant/components/assist_pipeline/__init__.py", line 26, in <module>
    from .websocket_api import async_register_websocket_api
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/homeassistant/components/assist_pipeline/websocket_api.py", line 31, in <module>
    from .vad import VoiceCommandSegmenter
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/homeassistant/components/assist_pipeline/vad.py", line 4, in <module>
    import webrtcvad
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/webrtcvad.py", line 8, in <module>
    __version__ = pkg_resources.get_distribution('webrtcvad').version
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 478, in get_distribution
    dist = get_provider(dist)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 354, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 795, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'webrtcvad' distribution was not found and is required by the application
2023-07-07 17:25:00.289 ERROR (MainThread) [homeassistant.setup] Setup failed for cloud: Unable to import component: Exception importing homeassistant.components.cloud
2023-07-07 17:25:00.933 WARNING (MainThread) [homeassistant.components.number] custom_components.xiaomi_miot_raw.number::MiotNumberInput is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.
2023-07-07 17:25:06.382 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/Users/liuzhou/.homeassistant/custom_components/xiaomi_miot_raw/basic_dev_class.py", line 554, in create_sub_entities
    self._hass.data[DOMAIN]['add_handler']['number'][self._entry_id](num_to_add, update_before_add=True)
KeyError: 'number'
2023-07-07 17:25:11.425 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-07-07 17:25:11.426 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-07-07 17:25:11.426 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-07-07 17:25:11.428 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-07-07 17:25:11.483 ERROR (MainThread) [homeassistant.components.sensor] Platform xiaomi_miot_raw does not generate unique IDs. ID normalcd1-cloud-280712-cooker_status is already used by sensor.normalcd1_cloud_280712_status - ignoring xiaomi_miot_raw.normalcd1-cloud-280712-status
2023-07-07 17:25:11.485 ERROR (MainThread) [homeassistant.components.sensor] Platform xiaomi_miot_raw does not generate unique IDs. ID normalcd1-cloud-280712-cooker_cook_mode is already used by sensor.normalcd1_cloud_280712_mode - ignoring xiaomi_miot_raw.normalcd1-cloud-280712-mode
2023-07-07 17:25:11.576 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing component homeassistant.components.assist_pipeline
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/homeassistant/components/assist_pipeline/__init__.py", line 26, in <module>
    from .websocket_api import async_register_websocket_api
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/homeassistant/components/assist_pipeline/websocket_api.py", line 31, in <module>
    from .vad import VoiceCommandSegmenter
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/homeassistant/components/assist_pipeline/vad.py", line 4, in <module>
    import webrtcvad
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/webrtcvad.py", line 8, in <module>
    __version__ = pkg_resources.get_distribution('webrtcvad').version
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 478, in get_distribution
    dist = get_provider(dist)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 354, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 795, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'webrtcvad' distribution was not found and is required by the application
2023-07-07 17:25:11.578 ERROR (MainThread) [homeassistant.setup] Setup failed for assist_pipeline: Unable to import component: Exception importing homeassistant.components.assist_pipeline
2023-07-07 17:25:16.685 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-07-07 17:25:16.686 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-07-07 17:25:16.686 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-07-07 17:25:16.687 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-07-07 17:25:16.687 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-07-07 17:25:16.687 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-07-07 17:25:16.688 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-07-07 17:25:16.689 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-07-07 17:25:16.690 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-07-07 17:25:16.752 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing component homeassistant.components.mobile_app
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/homeassistant/components/mobile_app/__init__.py", line 5, in <module>
    from homeassistant.components import cloud, notify as hass_notify
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/homeassistant/components/cloud/__init__.py", line 35, in <module>
    from . import account_link, http_api
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/homeassistant/components/cloud/http_api.py", line 20, in <module>
    from homeassistant.components import assist_pipeline, conversation, websocket_api
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/homeassistant/components/assist_pipeline/__init__.py", line 26, in <module>
    from .websocket_api import async_register_websocket_api
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/homeassistant/components/assist_pipeline/websocket_api.py", line 31, in <module>
    from .vad import VoiceCommandSegmenter
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/homeassistant/components/assist_pipeline/vad.py", line 4, in <module>
    import webrtcvad
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/webrtcvad.py", line 8, in <module>
    __version__ = pkg_resources.get_distribution('webrtcvad').version
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 478, in get_distribution
    dist = get_provider(dist)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 354, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 795, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'webrtcvad' distribution was not found and is required by the application
2023-07-07 17:25:16.758 ERROR (MainThread) [homeassistant.setup] Setup failed for mobile_app: Unable to import component: Exception importing homeassistant.components.mobile_app
2023-07-07 17:25:16.768 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:16.770 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:16.772 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:16.774 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:16.776 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:16.787 ERROR (MainThread) [homeassistant.setup] Unable to set up dependencies of default_config. Setup failed for dependencies: assist_pipeline, cloud, mobile_app
2023-07-07 17:25:16.788 ERROR (MainThread) [homeassistant.setup] Setup failed for default_config: (DependencyError(...), 'Could not setup dependencies: assist_pipeline, cloud, mobile_app')
2023-07-07 17:25:16.808 ERROR (MainThread) [homeassistant.components.climate] Platform xiaomi_miot_raw does not generate unique IDs. ID miotir-cloud-190208 is already used by climate.miotir_cloud_190208 - ignoring xiaomi_miot_raw.miotir-cloud-190208
2023-07-07 17:25:21.824 WARNING (MainThread) [homeassistant.components.media_player] Setup of media_player platform xiaomi_miot_raw is taking over 10 seconds.
2023-07-07 17:25:21.825 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/Users/liuzhou/.homeassistant/custom_components/xiaomi_miot_raw/basic_dev_class.py", line 556, in create_sub_entities
    self._hass.data[DOMAIN]['add_handler']['select'][self._entry_id](sel_to_add, update_before_add=True)
KeyError: 'select'
2023-07-07 17:25:21.829 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:21.831 ERROR (MainThread) [homeassistant.components.sensor] Platform xiaomi_miot_raw does not generate unique IDs. ID normalcd1-cloud-280712 is already used by sensor.normalcd1_cloud_280712 - ignoring xiaomi_miot_raw.normalcd1-cloud-280712
2023-07-07 17:25:21.832 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:21.877 ERROR (MainThread) [homeassistant.components.select] Platform xiaomi_miot_raw does not generate unique IDs. ID normalcd1-cloud-280712-a_l is already used by select.normalcd1_cloud_280712_a_l - ignoring xiaomi_miot_raw.normalcd1-cloud-280712-a_l
2023-07-07 17:25:26.882 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:26.886 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:26.894 WARNING (MainThread) [homeassistant.components.fan] Setup of fan platform xiaomi_miot_raw is taking over 10 seconds.
2023-07-07 17:25:26.894 WARNING (MainThread) [homeassistant.components.fan] Setup of fan platform xiaomi_miot_raw is taking over 10 seconds.
2023-07-07 17:25:26.896 WARNING (MainThread) [homeassistant.components.fan] Setup of fan platform xiaomi_miot_raw is taking over 10 seconds.
2023-07-07 17:25:26.899 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:26.901 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:26.902 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:26.904 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:26.905 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:26.908 WARNING (MainThread) [homeassistant.components.sensor] Updating xiaomi_miot_raw sensor took longer than the scheduled update interval 0:00:05
2023-07-07 17:25:26.909 WARNING (MainThread) [homeassistant.components.sensor] Updating xiaomi_miot_raw sensor took longer than the scheduled update interval 0:00:05
2023-07-07 17:25:26.910 WARNING (MainThread) [homeassistant.components.sensor] Updating xiaomi_miot_raw sensor took longer than the scheduled update interval 0:00:05
2023-07-07 17:25:26.911 WARNING (MainThread) [homeassistant.components.sensor] Updating xiaomi_miot_raw sensor took longer than the scheduled update interval 0:00:05
2023-07-07 17:25:26.911 WARNING (MainThread) [homeassistant.components.sensor] Updating xiaomi_miot_raw sensor took longer than the scheduled update interval 0:00:05
2023-07-07 17:25:31.930 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-07-07 17:25:31.931 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-07-07 17:25:31.932 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-07-07 17:25:31.933 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-07-07 17:25:31.934 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-07-07 17:25:31.935 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-07-07 17:25:31.936 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-07-07 17:25:31.937 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-07-07 17:25:31.939 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-07-07 17:25:31.939 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-07-07 17:25:31.941 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-07-07 17:25:31.942 WARNING (MainThread) [homeassistant.components.light] Setup of light platform xiaomi_miot_raw is taking over 10 seconds.
2023-07-07 17:25:31.943 WARNING (MainThread) [homeassistant.components.light] Setup of light platform xiaomi_miot_raw is taking over 10 seconds.
2023-07-07 17:25:31.944 WARNING (MainThread) [homeassistant.components.light] Setup of light platform xiaomi_miot_raw is taking over 10 seconds.
2023-07-07 17:25:31.945 WARNING (MainThread) [homeassistant.components.light] Setup of light platform xiaomi_miot_raw is taking over 10 seconds.
2023-07-07 17:25:31.946 WARNING (MainThread) [homeassistant.components.light] Setup of light platform xiaomi_miot_raw is taking over 10 seconds.
2023-07-07 17:25:31.947 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform xiaomi_miot_raw is taking over 10 seconds.
2023-07-07 17:25:31.954 WARNING (MainThread) [homeassistant.components.cover] Updating xiaomi_miot_raw cover took longer than the scheduled update interval 0:00:02
2023-07-07 17:25:31.984 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:31.986 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:31.988 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:31.989 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:31.998 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:32.040 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:32.044 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:32.048 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:32.051 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:32.064 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:32.065 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:32.106 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:32.182 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:32.215 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:32.216 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:32.219 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:32.222 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:32.223 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:32.225 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:32.263 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:36.955 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:36.991 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:36.995 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:36.995 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:36.996 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:36.998 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:38.022 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:38.326 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:42.033 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:42.035 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:42.037 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:42.039 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:42.040 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:42.042 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:42.048 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:42.055 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:42.056 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:42.074 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:42.075 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:42.096 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:42.109 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:42.112 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:42.225 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:42.320 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:42.321 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:42.322 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:44.218 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:46.940 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:46.991 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:46.998 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:47.000 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:47.001 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:47.002 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:47.977 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:50.104 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:51.992 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:52.017 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:52.019 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:52.020 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:52.028 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:52.029 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:52.039 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:52.058 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:52.059 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:52.068 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:52.081 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:52.135 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:52.137 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:52.138 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:52.256 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:52.265 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:52.276 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:52.279 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:55.958 ERROR (MainThread) [custom_components.xiaomi_miot_raw] The main device of 小米无线开关(255.255.255.255) is still not ready after 30 seconds!
2023-07-07 17:25:55.963 WARNING (MainThread) [homeassistant.components.select] Platform xiaomi_miot_raw not ready yet: None; Retrying in background in 30 seconds
2023-07-07 17:25:55.965 WARNING (MainThread) [homeassistant.bootstrap] Support for the running Python version 3.10.6 is deprecated and will be removed in Home Assistant 2023.8; Please upgrade Python to 3.11
2023-07-07 17:25:56.402 WARNING (SyncWorker_1) [scapy.runtime] No IPv4 address found on en5 !
2023-07-07 17:25:56.451 WARNING (SyncWorker_1) [scapy.runtime] No IPv4 address found on en9 !
2023-07-07 17:25:56.474 WARNING (SyncWorker_1) [scapy.runtime] more No IPv4 address found on en8 !
2023-07-07 17:25:57.240 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:57.286 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:57.322 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:57.325 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:57.336 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:57.348 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:57.580 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:25:58.069 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:02.021 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:02.024 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:02.063 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:02.064 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:02.066 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:02.103 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:02.113 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:02.117 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:02.132 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:02.358 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:02.360 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:02.361 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:02.362 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:02.363 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:02.365 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:02.366 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:02.367 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:02.481 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:03.264 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:05.982 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-07-07 17:26:07.277 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:07.281 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:07.290 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:07.293 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:07.295 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:07.298 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:07.993 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:09.108 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:12.019 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:12.020 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:12.045 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:12.048 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:12.055 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:12.112 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:12.129 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:12.135 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:12.229 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:12.259 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:12.266 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:12.295 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:12.301 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:12.303 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:12.304 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:12.305 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:12.306 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:12.317 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:15.106 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:17.353 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:17.355 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:17.356 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:17.358 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:17.361 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:17.363 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:18.030 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:21.120 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:22.006 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:22.010 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:22.064 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:22.066 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:22.067 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:22.101 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:22.115 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:22.119 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:22.249 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:22.269 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:22.273 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:22.274 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:22.276 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:22.278 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:22.281 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:22.287 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:22.289 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:22.295 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:25.990 ERROR (MainThread) [custom_components.xiaomi_miot_raw] The main device of 小米无线开关(255.255.255.255) is still not ready after 30 seconds!
2023-07-07 17:26:27.170 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:27.288 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:27.290 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:27.293 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:27.295 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:27.296 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:27.299 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:28.005 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:32.027 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:32.030 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:32.101 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:32.104 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:32.107 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:32.110 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:32.150 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:32.153 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:32.156 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:32.294 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:32.297 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:32.299 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:32.301 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:32.633 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:32.635 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:32.637 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:32.639 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:32.640 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:33.134 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:34.825 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/selector_events.py", line 1027, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/ssdp.py", line 264, in datagram_received
    self.on_data(request_line, headers)
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 338, in _on_data
    self._send_response_rootdevice(remote_addr)
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 401, in _send_response_rootdevice
    self._send_response(
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 469, in _send_response
    self._response_socket.sendto(packet, remote_addr)
OSError: [Errno 65] No route to host
2023-07-07 17:26:35.809 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/selector_events.py", line 1027, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/ssdp.py", line 264, in datagram_received
    self.on_data(request_line, headers)
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 338, in _on_data
    self._send_response_rootdevice(remote_addr)
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 401, in _send_response_rootdevice
    self._send_response(
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 469, in _send_response
    self._response_socket.sendto(packet, remote_addr)
OSError: [Errno 65] No route to host
2023-07-07 17:26:37.004 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/selector_events.py", line 1027, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/ssdp.py", line 264, in datagram_received
    self.on_data(request_line, headers)
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 338, in _on_data
    self._send_response_rootdevice(remote_addr)
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 401, in _send_response_rootdevice
    self._send_response(
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 469, in _send_response
    self._response_socket.sendto(packet, remote_addr)
OSError: [Errno 65] No route to host
2023-07-07 17:26:37.309 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:37.316 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:37.322 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:37.346 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:37.348 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:37.495 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:37.896 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/selector_events.py", line 1027, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/ssdp.py", line 264, in datagram_received
    self.on_data(request_line, headers)
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 338, in _on_data
    self._send_response_rootdevice(remote_addr)
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 401, in _send_response_rootdevice
    self._send_response(
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 469, in _send_response
    self._response_socket.sendto(packet, remote_addr)
OSError: [Errno 65] No route to host
2023-07-07 17:26:38.009 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:39.162 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:42.008 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:42.014 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:42.052 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:42.056 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:42.058 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:42.082 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:42.110 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:42.114 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:42.117 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:42.242 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:42.266 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:42.275 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:42.276 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:42.283 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:42.289 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:42.291 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:42.297 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:42.298 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:45.118 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:47.305 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:47.306 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:47.307 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:47.308 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:47.309 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:47.311 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:48.064 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:51.250 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:52.047 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:52.048 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:52.075 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:52.076 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:52.078 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:52.079 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:52.113 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:52.118 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:52.122 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:52.236 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:52.271 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:52.283 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:52.284 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:52.285 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:52.346 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:52.348 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:52.349 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:52.350 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:57.101 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:57.290 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:57.292 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:57.295 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:57.297 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:57.299 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:57.301 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:26:58.024 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:02.012 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:02.014 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:02.053 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:02.060 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:02.062 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:02.072 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:02.110 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:02.126 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:02.129 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:02.252 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:02.271 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:02.283 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:02.287 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:02.292 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:02.296 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:02.297 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:02.299 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:02.488 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:03.104 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:07.293 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:07.295 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:07.297 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:07.305 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:07.642 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:07.643 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:08.200 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:09.119 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:12.052 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:12.054 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:12.058 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:12.061 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:12.062 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:12.079 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:12.114 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:12.122 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:12.124 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:12.235 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:12.267 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:12.273 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:12.343 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:12.345 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:12.346 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:12.348 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:12.350 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:12.352 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:15.249 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:17.290 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:17.305 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:17.308 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:17.339 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:17.341 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:17.343 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:18.024 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:21.165 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:22.042 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:22.044 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:22.083 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:22.085 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:22.087 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:22.089 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:22.244 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:22.245 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:22.247 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:22.248 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:22.301 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:22.304 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:22.306 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:22.309 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:22.311 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:22.316 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:22.318 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:22.320 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:27.117 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:27.288 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:27.299 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:27.300 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:27.314 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:27.315 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:27.316 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:28.035 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:32.010 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:32.012 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:32.056 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:32.059 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:32.061 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:32.082 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:32.113 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:32.124 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:32.127 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:32.239 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:32.290 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:32.293 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:32.295 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:32.309 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:32.313 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:32.327 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:32.330 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:32.333 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:33.106 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:35.994 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-07-07 17:27:37.320 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:37.330 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:37.331 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:37.332 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:37.333 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:37.333 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:38.031 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:39.148 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:42.016 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:42.019 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:42.065 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:42.069 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:42.071 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:42.171 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:42.174 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:42.328 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:42.330 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:42.332 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:42.334 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:42.335 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:42.338 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:42.340 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:42.341 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:42.543 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:42.546 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:42.581 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:45.108 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:47.345 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:47.346 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:47.349 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:47.351 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:47.352 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:47.353 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:48.034 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:51.113 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:52.091 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:52.094 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:52.097 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:52.098 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:52.100 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:52.102 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:52.126 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:52.130 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:52.132 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:52.307 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:52.310 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:52.314 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:52.316 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:52.318 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:52.320 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:52.322 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:52.324 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:52.325 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:55.997 ERROR (MainThread) [custom_components.xiaomi_miot_raw] The main device of 小米无线开关(255.255.255.255) is still not ready after 30 seconds!
2023-07-07 17:27:57.099 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:57.287 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:57.290 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:57.294 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:57.304 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:57.311 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:57.318 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:27:58.087 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:02.039 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:02.041 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:02.091 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:02.092 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:02.093 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:02.095 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:02.147 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:02.149 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:02.150 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:02.240 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:02.277 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:02.278 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:02.290 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:02.295 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:02.299 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:02.301 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:02.309 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:02.311 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:03.211 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:07.482 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:07.484 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:07.486 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:07.486 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:07.488 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:07.536 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:08.103 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:09.102 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:12.156 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:12.160 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:12.162 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:12.164 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:12.166 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:12.168 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:12.173 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:12.255 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:12.260 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:12.304 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:12.307 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:12.314 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:12.316 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:12.318 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:12.326 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:12.330 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:12.345 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:12.355 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:15.102 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:17.388 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:17.391 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:17.394 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:17.396 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:17.398 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:17.400 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:18.087 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:21.112 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:22.040 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:22.043 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:22.148 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:22.154 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:22.156 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:22.157 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:22.159 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:22.161 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:22.197 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:22.244 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:22.301 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:22.305 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:22.308 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:22.340 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:22.343 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:22.345 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:22.348 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:22.350 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:27.105 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:27.349 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:27.350 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:27.352 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:27.352 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:27.354 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:27.355 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:28.064 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:32.350 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:32.352 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:32.353 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:32.356 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:32.357 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:32.359 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:32.361 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:32.363 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:32.704 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:32.708 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:32.715 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:32.717 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:32.719 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:32.720 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:32.722 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:32.722 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:32.724 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:32.731 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:33.170 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:35.875 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/selector_events.py", line 1027, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/ssdp.py", line 264, in datagram_received
    self.on_data(request_line, headers)
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 338, in _on_data
    self._send_response_rootdevice(remote_addr)
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 401, in _send_response_rootdevice
    self._send_response(
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 469, in _send_response
    self._response_socket.sendto(packet, remote_addr)
OSError: [Errno 65] No route to host
2023-07-07 17:28:36.904 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/selector_events.py", line 1027, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/ssdp.py", line 264, in datagram_received
    self.on_data(request_line, headers)
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 338, in _on_data
    self._send_response_rootdevice(remote_addr)
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 401, in _send_response_rootdevice
    self._send_response(
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 469, in _send_response
    self._response_socket.sendto(packet, remote_addr)
OSError: [Errno 65] No route to host
2023-07-07 17:28:38.022 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/selector_events.py", line 1027, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/ssdp.py", line 264, in datagram_received
    self.on_data(request_line, headers)
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 338, in _on_data
    self._send_response_rootdevice(remote_addr)
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 401, in _send_response_rootdevice
    self._send_response(
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 469, in _send_response
    self._response_socket.sendto(packet, remote_addr)
OSError: [Errno 65] No route to host
2023-07-07 17:28:38.395 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:38.399 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:38.402 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:38.403 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:38.405 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:38.406 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:38.408 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:39.379 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:42.139 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:42.141 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:42.142 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:42.144 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:42.145 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:42.146 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:42.147 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:42.387 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:42.392 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:42.394 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:42.396 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:42.398 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:42.400 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:42.401 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:42.403 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:42.405 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:42.406 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:42.407 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:45.172 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:47.301 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:47.312 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:47.314 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:47.317 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:47.320 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:47.325 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:48.067 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:51.411 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:52.312 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:52.313 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:52.315 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:52.316 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:52.317 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:52.318 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:52.319 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:52.320 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:52.321 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:52.399 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:52.402 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:52.861 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:52.864 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:52.865 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:52.973 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:52.975 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:52.976 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:52.978 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:57.158 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:57.321 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:57.325 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:57.327 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:57.338 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:57.340 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:57.342 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:28:58.107 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:02.068 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:02.071 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:02.074 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:02.076 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:02.077 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:02.094 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:02.126 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:02.130 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:02.142 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:02.252 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:02.441 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:02.445 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:02.448 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:02.449 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:02.451 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:02.453 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:02.455 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:02.457 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:03.106 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:07.301 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:07.314 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:07.321 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:07.324 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:07.326 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:07.327 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:08.062 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:09.174 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:12.058 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:12.060 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:12.067 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:12.085 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:12.088 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:12.137 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:12.139 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:12.155 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:12.156 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:12.250 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:12.283 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:12.324 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:12.327 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:12.329 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:12.338 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:12.349 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:12.351 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:12.352 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:15.106 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:17.301 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:17.309 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:17.397 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:17.400 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:17.403 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:17.405 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:18.123 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:21.116 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:22.070 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:22.072 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:22.074 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:22.075 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:22.077 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:22.097 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:22.152 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:22.153 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:22.159 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:22.309 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:22.310 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:22.311 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:22.326 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:22.357 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:22.359 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:22.360 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:22.462 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:27.110 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:27.298 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:27.315 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:27.322 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:27.325 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:27.332 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:27.334 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:28.127 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:32.094 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:32.095 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:32.096 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:32.096 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:32.097 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:32.101 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:32.122 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:32.145 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:32.284 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:32.286 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:32.294 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:32.316 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:32.319 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:32.322 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:32.324 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:32.331 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:33.123 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:36.004 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-07-07 17:29:37.347 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:37.350 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:37.352 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:37.354 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:37.355 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:37.357 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:38.118 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:39.209 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:42.103 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:42.105 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:42.107 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:42.110 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:42.112 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:42.114 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:42.143 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:42.155 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:42.302 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:42.304 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:42.305 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:42.349 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:42.352 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:42.354 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:42.356 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:42.629 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:29:42.722 ERROR (MainThread) [homeassistant.config_entries] Error calling entry remove callback 1875***0567 for xiaomi_miot_raw
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/homeassistant/config_entries.py", line 582, in async_remove
    await component.async_remove_entry(hass, self)
  File "/Users/liuzhou/.homeassistant/custom_components/xiaomi_miot_raw/__init__.py", line 185, in async_remove_entry
    await asyncio.gather(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/homeassistant/config_entries.py", line 1065, in async_remove
    raise UnknownEntry
homeassistant.config_entries.UnknownEntry
2023-07-07 17:29:56.007 ERROR (MainThread) [custom_components.xiaomi_miot_raw] The main device of 小米无线开关(255.255.255.255) is still not ready after 30 seconds!
2023-07-07 17:30:35.044 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/selector_events.py", line 1027, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/ssdp.py", line 264, in datagram_received
    self.on_data(request_line, headers)
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 338, in _on_data
    self._send_response_rootdevice(remote_addr)
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 401, in _send_response_rootdevice
    self._send_response(
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 469, in _send_response
    self._response_socket.sendto(packet, remote_addr)
OSError: [Errno 65] No route to host
2023-07-07 17:30:35.993 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/selector_events.py", line 1027, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/ssdp.py", line 264, in datagram_received
    self.on_data(request_line, headers)
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 338, in _on_data
    self._send_response_rootdevice(remote_addr)
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 401, in _send_response_rootdevice
    self._send_response(
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 469, in _send_response
    self._response_socket.sendto(packet, remote_addr)
OSError: [Errno 65] No route to host
2023-07-07 17:30:37.004 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/selector_events.py", line 1027, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/ssdp.py", line 264, in datagram_received
    self.on_data(request_line, headers)
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 338, in _on_data
    self._send_response_rootdevice(remote_addr)
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 401, in _send_response_rootdevice
    self._send_response(
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 469, in _send_response
    self._response_socket.sendto(packet, remote_addr)
OSError: [Errno 65] No route to host
2023-07-07 17:30:38.138 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback _SelectorDatagramTransport._read_ready()
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/selector_events.py", line 1027, in _read_ready
    self._protocol.datagram_received(data, addr)
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/ssdp.py", line 264, in datagram_received
    self.on_data(request_line, headers)
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 338, in _on_data
    self._send_response_rootdevice(remote_addr)
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 401, in _send_response_rootdevice
    self._send_response(
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 469, in _send_response
    self._response_socket.sendto(packet, remote_addr)
OSError: [Errno 65] No route to host
2023-07-07 17:30:59.127 ERROR (MainThread) [miio.miioprotocol] failed to send msg: [Errno 13] Permission denied
2023-07-07 17:30:59.157 ERROR (MainThread) [miio.miioprotocol] failed to send msg: [Errno 13] Permission denied
2023-07-07 17:30:59.175 ERROR (MainThread) [miio.miioprotocol] failed to send msg: [Errno 13] Permission denied
2023-07-07 17:30:59.199 ERROR (MainThread) [miio.miioprotocol] failed to send msg: [Errno 13] Permission denied
2023-07-07 17:30:59.216 ERROR (MainThread) [miio.miioprotocol] failed to send msg: [Errno 13] Permission denied
2023-07-07 17:30:59.233 ERROR (MainThread) [miio.miioprotocol] failed to send msg: [Errno 13] Permission denied
2023-07-07 17:30:59.256 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/Users/liuzhou/.homeassistant/custom_components/xiaomi_miot_raw/config_flow.py", line 137, in guess_mp_from_model
    a = await cs.get(url_all)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/homeassistant/config_entries.py", line 845, in async_init
    flow, result = await task
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/homeassistant/config_entries.py", line 873, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/Users/liuzhou/.homeassistant/custom_components/xiaomi_miot_raw/config_flow.py", line 618, in async_step_batch_add
    return await self.async_step_user({
  File "/Users/liuzhou/.homeassistant/custom_components/xiaomi_miot_raw/config_flow.py", line 252, in async_step_user
    return await self.async_step_localinfo({
  File "/Users/liuzhou/.homeassistant/custom_components/xiaomi_miot_raw/config_flow.py", line 366, in async_step_localinfo
    return await self.async_step_xiaoai({
  File "/Users/liuzhou/.homeassistant/custom_components/xiaomi_miot_raw/config_flow.py", line 571, in async_step_xiaoai
    self._info = await guess_mp_from_model(self.hass, self._model)
  File "/Users/liuzhou/.homeassistant/custom_components/xiaomi_miot_raw/config_flow.py", line 135, in guess_mp_from_model
    with async_timeout.timeout(10):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/async_timeout/__init__.py", line 116, in __exit__
    self._do_exit(exc_type)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
2023-07-07 17:30:59.269 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/Users/liuzhou/.homeassistant/custom_components/xiaomi_miot_raw/config_flow.py", line 137, in guess_mp_from_model
    a = await cs.get(url_all)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/aiohttp/connector.py", line 1152, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/homeassistant/config_entries.py", line 845, in async_init
    flow, result = await task
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/homeassistant/config_entries.py", line 873, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/Users/liuzhou/.homeassistant/custom_components/xiaomi_miot_raw/config_flow.py", line 618, in async_step_batch_add
    return await self.async_step_user({
  File "/Users/liuzhou/.homeassistant/custom_components/xiaomi_miot_raw/config_flow.py", line 252, in async_step_user
    return await self.async_step_localinfo({
  File "/Users/liuzhou/.homeassistant/custom_components/xiaomi_miot_raw/config_flow.py", line 366, in async_step_localinfo
    return await self.async_step_xiaoai({
  File "/Users/liuzhou/.homeassistant/custom_components/xiaomi_miot_raw/config_flow.py", line 571, in async_step_xiaoai
    self._info = await guess_mp_from_model(self.hass, self._model)
  File "/Users/liuzhou/.homeassistant/custom_components/xiaomi_miot_raw/config_flow.py", line 135, in guess_mp_from_model
    with async_timeout.timeout(10):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/async_timeout/__init__.py", line 116, in __exit__
    self._do_exit(exc_type)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/async_timeout/__init__.py", line 212, in _do_exit
    raise asyncio.TimeoutError
asyncio.exceptions.TimeoutError
2023-07-07 17:31:06.456 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:06.493 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:11.523 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:11.531 WARNING (MainThread) [homeassistant.components.water_heater] Setup of water_heater platform xiaomi_miot_raw is taking over 10 seconds.
2023-07-07 17:31:11.554 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/Users/liuzhou/.homeassistant/custom_components/xiaomi_miot_raw/basic_dev_class.py", line 554, in create_sub_entities
    self._hass.data[DOMAIN]['add_handler']['number'][self._entry_id](num_to_add, update_before_add=True)
KeyError: '1131c3517071af173dd61e257ff8f160'
2023-07-07 17:31:11.577 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:11.609 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:11.735 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:11.747 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:11.783 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:11.791 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:16.596 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:16.614 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:16.787 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:16.808 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:17.559 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:21.588 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:21.615 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:21.653 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:21.792 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:21.822 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:21.831 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:23.568 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:26.575 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:26.601 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:26.799 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:26.865 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:29.535 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:31.640 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:31.642 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:31.673 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:31.780 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:31.808 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:31.833 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:35.528 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:36.590 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:36.596 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:36.777 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:36.785 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:41.552 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:41.584 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:41.610 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:41.699 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:41.799 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:41.819 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
2023-07-07 17:31:41.828 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] 小米账号登录信息失效
