2023-03-17 14:15:51.046 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration colorfulclouds which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-03-17 14:15:51.049 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration ics_calendar which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-03-17 14:15:51.050 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_miot_raw which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-03-17 14:15:51.050 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-03-17 14:15:59.527 WARNING (MainThread) [homeassistant.components.number] custom_components.xiaomi_miot_raw.number::MiotNumberInput is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.
2023-03-17 14:16:04.681 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-03-17 14:16:04.682 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-03-17 14:16:04.682 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-03-17 14:16:04.683 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-03-17 14:16:04.683 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-03-17 14:16:04.684 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-03-17 14:16:04.684 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-03-17 14:16:04.684 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-03-17 14:16:04.685 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-03-17 14:16:04.685 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-03-17 14:16:04.685 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-03-17 14:16:04.705 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] Timeout while loading MiCloud device list
2023-03-17 14:16:09.740 ERROR (MainThread) [homeassistant.components.climate] Platform xiaomi_miot_raw does not generate unique IDs. ID miotir-cloud-190208 is already used by climate.miotir_cloud_190208 - ignoring xiaomi_miot_raw.miotir-cloud-190208
2023-03-17 14:16:09.752 WARNING (MainThread) [homeassistant.components.media_player] Setup of media_player platform xiaomi_miot_raw is taking over 10 seconds.
2023-03-17 14:16:09.753 WARNING (MainThread) [homeassistant.components.calendar] Setup of calendar platform ics_calendar is taking over 10 seconds.
2023-03-17 14:16:09.758 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] Error while requesting MIoT api /miotspec/prop/get : 
2023-03-17 14:16:14.827 WARNING (MainThread) [homeassistant.components.number] Setup of number platform xiaomi_miot_raw is taking over 10 seconds.
2023-03-17 14:16:14.828 WARNING (MainThread) [homeassistant.components.binary_sensor] Setup of binary_sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-03-17 14:16:14.829 WARNING (MainThread) [homeassistant.components.binary_sensor] Setup of binary_sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-03-17 14:16:14.829 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-03-17 14:16:14.830 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-03-17 14:16:14.830 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-03-17 14:16:14.830 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-03-17 14:16:14.830 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-03-17 14:16:14.831 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-03-17 14:16:14.831 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-03-17 14:16:14.832 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-03-17 14:16:14.832 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-03-17 14:16:14.832 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-03-17 14:16:14.833 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-03-17 14:16:14.833 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-03-17 14:16:14.834 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-03-17 14:16:14.834 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-03-17 14:16:14.834 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-03-17 14:16:14.834 WARNING (MainThread) [homeassistant.components.fan] Setup of fan platform xiaomi_miot_raw is taking over 10 seconds.
2023-03-17 14:16:14.835 WARNING (MainThread) [homeassistant.components.fan] Setup of fan platform xiaomi_miot_raw is taking over 10 seconds.
2023-03-17 14:16:14.835 WARNING (MainThread) [homeassistant.components.fan] Setup of fan platform xiaomi_miot_raw is taking over 10 seconds.
2023-03-17 14:16:14.835 WARNING (MainThread) [homeassistant.components.cover] Setup of cover platform xiaomi_miot_raw is taking over 10 seconds.
2023-03-17 14:16:14.854 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] Error while requesting MIoT api /miotspec/prop/get : 
2023-03-17 14:16:15.675 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/Users/liuzhou/.homeassistant/custom_components/xiaomi_miot_raw/basic_dev_class.py", line 554, in create_sub_entities
    self._hass.data[DOMAIN]['add_handler']['number'][self._entry_id](num_to_add, update_before_add=True)
KeyError: 'number'
2023-03-17 14:16:19.764 WARNING (MainThread) [homeassistant.helpers.entity] Update of calendar.wo_de_ri_li is taking over 10 seconds
2023-03-17 14:16:33.015 ERROR (SyncWorker_4) [custom_components.ics_calendar.calendar] 我的日历: Failed to open url: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:997)
2023-03-17 14:16:38.858 ERROR (MainThread) [custom_components.xiaomi_miot_raw] The main device of 小米无线开关(255.255.255.255) is still not ready after 30 seconds!
2023-03-17 14:16:38.864 WARNING (MainThread) [homeassistant.components.select] Platform xiaomi_miot_raw not ready yet: None; Retrying in background in 30 seconds
2023-03-17 14:16:43.669 WARNING (SyncWorker_4) [scapy.runtime] No IPv4 address found on en5 !
2023-03-17 14:16:43.700 WARNING (SyncWorker_4) [scapy.runtime] No IPv4 address found on ap1 !
2023-03-17 14:16:43.739 WARNING (SyncWorker_4) [scapy.runtime] more No IPv4 address found on awdl0 !
2023-03-17 14:16:48.896 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-03-17 14:17:08.940 ERROR (MainThread) [custom_components.xiaomi_miot_raw] The main device of 小米无线开关(255.255.255.255) is still not ready after 30 seconds!
2023-03-17 14:17:19.760 WARNING (MainThread) [homeassistant.helpers.entity] Update of calendar.jia_qi is taking over 10 seconds
2023-03-17 14:18:06.050 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 336, in _async_on_data
    await self._async_send_response_rootdevice(remote_addr)
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 401, in _async_send_response_rootdevice
    await self._async_send_response(
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 469, in _async_send_response
    self._response_socket.sendto(packet, remote_addr)
OSError: [Errno 65] No route to host
2023-03-17 14:18:07.072 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 336, in _async_on_data
    await self._async_send_response_rootdevice(remote_addr)
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 401, in _async_send_response_rootdevice
    await self._async_send_response(
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 469, in _async_send_response
    self._response_socket.sendto(packet, remote_addr)
OSError: [Errno 65] No route to host
2023-03-17 14:18:08.095 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 336, in _async_on_data
    await self._async_send_response_rootdevice(remote_addr)
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 401, in _async_send_response_rootdevice
    await self._async_send_response(
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 469, in _async_send_response
    self._response_socket.sendto(packet, remote_addr)
OSError: [Errno 65] No route to host
2023-03-17 14:18:09.758 WARNING (MainThread) [homeassistant.components.calendar] Updating ics_calendar calendar took longer than the scheduled update interval 0:01:00
2023-03-17 14:18:18.944 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-03-17 14:18:38.947 ERROR (MainThread) [custom_components.xiaomi_miot_raw] The main device of 小米无线开关(255.255.255.255) is still not ready after 30 seconds!
2023-03-17 14:19:09.758 WARNING (MainThread) [homeassistant.components.calendar] Updating ics_calendar calendar took longer than the scheduled update interval 0:01:00
2023-03-17 14:19:49.556 WARNING (Thread-2 (_do_shutdown)) [homeassistant.util.executor] Thread[SyncWorker_4] is still running at shutdown: File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 73, in download_calendar
    self._download_data()
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 159, in _download_data
    with CalendarData.opener_lock:
2023-03-17 14:19:49.662 WARNING (Thread-2 (_do_shutdown)) [homeassistant.util.executor] Thread[SyncWorker_0] is still running at shutdown: File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 73, in download_calendar
    self._download_data()
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 159, in _download_data
    with CalendarData.opener_lock:
2023-03-17 14:19:49.765 WARNING (Thread-2 (_do_shutdown)) [homeassistant.util.executor] Thread[SyncWorker_5] is still running at shutdown: File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 73, in download_calendar
    self._download_data()
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 159, in _download_data
    with CalendarData.opener_lock:
2023-03-17 14:19:49.871 WARNING (Thread-2 (_do_shutdown)) [homeassistant.util.executor] Thread[SyncWorker_3] is still running at shutdown: File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 73, in download_calendar
    self._download_data()
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 159, in _download_data
    with CalendarData.opener_lock:
2023-03-17 14:19:49.976 WARNING (Thread-2 (_do_shutdown)) [homeassistant.util.executor] Thread[SyncWorker_2] is still running at shutdown: File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 73, in download_calendar
    self._download_data()
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 159, in _download_data
    with CalendarData.opener_lock:
2023-03-17 14:19:50.086 WARNING (Thread-2 (_do_shutdown)) [homeassistant.util.executor] Thread[SyncWorker_1] is still running at shutdown: File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 73, in download_calendar
    self._download_data()
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 162, in _download_data
    with urlopen(self._make_url()) as conn:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
2023-03-17 14:19:50.190 WARNING (Thread-2 (_do_shutdown)) [homeassistant.util.executor] Thread[SyncWorker_6] is still running at shutdown: File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendar.py", line 205, in update
    self.data.update()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/homeassistant/util/__init__.py", line 192, in wrapper
    result = method(*args, **kwargs)
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendar.py", line 287, in update
    if self._calendar_data.download_calendar():
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 73, in download_calendar
    self._download_data()
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 159, in _download_data
    with CalendarData.opener_lock:
2023-03-17 14:19:50.328 WARNING (Thread-2 (_do_shutdown)) [homeassistant.util.executor] Thread[SyncWorker_4] is still running at shutdown: File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 73, in download_calendar
    self._download_data()
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 159, in _download_data
    with CalendarData.opener_lock:
2023-03-17 14:19:50.467 WARNING (Thread-2 (_do_shutdown)) [homeassistant.util.executor] Thread[SyncWorker_0] is still running at shutdown: File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 73, in download_calendar
    self._download_data()
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 159, in _download_data
    with CalendarData.opener_lock:
2023-03-17 14:19:50.605 WARNING (Thread-2 (_do_shutdown)) [homeassistant.util.executor] Thread[SyncWorker_5] is still running at shutdown: File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 73, in download_calendar
    self._download_data()
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 159, in _download_data
    with CalendarData.opener_lock:
2023-03-17 14:19:50.739 WARNING (Thread-2 (_do_shutdown)) [homeassistant.util.executor] Thread[SyncWorker_3] is still running at shutdown: File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 73, in download_calendar
    self._download_data()
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 159, in _download_data
    with CalendarData.opener_lock:
2023-03-17 14:19:50.875 WARNING (Thread-2 (_do_shutdown)) [homeassistant.util.executor] Thread[SyncWorker_2] is still running at shutdown: File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 73, in download_calendar
    self._download_data()
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 159, in _download_data
    with CalendarData.opener_lock:
2023-03-17 14:19:51.009 WARNING (Thread-2 (_do_shutdown)) [homeassistant.util.executor] Thread[SyncWorker_1] is still running at shutdown: File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 73, in download_calendar
    self._download_data()
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 162, in _download_data
    with urlopen(self._make_url()) as conn:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
2023-03-17 14:19:51.148 WARNING (Thread-2 (_do_shutdown)) [homeassistant.util.executor] Thread[SyncWorker_6] is still running at shutdown: File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendar.py", line 205, in update
    self.data.update()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/homeassistant/util/__init__.py", line 192, in wrapper
    result = method(*args, **kwargs)
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendar.py", line 287, in update
    if self._calendar_data.download_calendar():
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 73, in download_calendar
    self._download_data()
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 159, in _download_data
    with CalendarData.opener_lock:
2023-03-17 14:19:59.561 WARNING (MainThread) [homeassistant.util.executor] Thread[SyncWorker_4] is still running at shutdown: File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 73, in download_calendar
    self._download_data()
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 159, in _download_data
    with CalendarData.opener_lock:
2023-03-17 14:19:59.668 WARNING (MainThread) [homeassistant.util.executor] Thread[SyncWorker_0] is still running at shutdown: File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 73, in download_calendar
    self._download_data()
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 159, in _download_data
    with CalendarData.opener_lock:
2023-03-17 14:19:59.774 WARNING (MainThread) [homeassistant.util.executor] Thread[SyncWorker_5] is still running at shutdown: File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 73, in download_calendar
    self._download_data()
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 159, in _download_data
    with CalendarData.opener_lock:
2023-03-17 14:19:59.881 WARNING (MainThread) [homeassistant.util.executor] Thread[SyncWorker_3] is still running at shutdown: File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 73, in download_calendar
    self._download_data()
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 159, in _download_data
    with CalendarData.opener_lock:
2023-03-17 14:19:59.988 WARNING (MainThread) [homeassistant.util.executor] Thread[SyncWorker_2] is still running at shutdown: File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 73, in download_calendar
    self._download_data()
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 159, in _download_data
    with CalendarData.opener_lock:
2023-03-17 14:20:00.093 WARNING (MainThread) [homeassistant.util.executor] Thread[SyncWorker_1] is still running at shutdown: File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 73, in download_calendar
    self._download_data()
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 162, in _download_data
    with urlopen(self._make_url()) as conn:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
2023-03-17 14:20:00.198 WARNING (MainThread) [homeassistant.util.executor] Thread[SyncWorker_6] is still running at shutdown: File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendar.py", line 205, in update
    self.data.update()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/homeassistant/util/__init__.py", line 192, in wrapper
    result = method(*args, **kwargs)
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendar.py", line 287, in update
    if self._calendar_data.download_calendar():
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 73, in download_calendar
    self._download_data()
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 159, in _download_data
    with CalendarData.opener_lock:
2023-03-17 14:20:00.334 WARNING (MainThread) [homeassistant.util.executor] Thread[SyncWorker_4] is still running at shutdown: File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 73, in download_calendar
    self._download_data()
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 159, in _download_data
    with CalendarData.opener_lock:
2023-03-17 14:20:00.469 WARNING (MainThread) [homeassistant.util.executor] Thread[SyncWorker_0] is still running at shutdown: File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 73, in download_calendar
    self._download_data()
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 159, in _download_data
    with CalendarData.opener_lock:
2023-03-17 14:20:00.605 WARNING (MainThread) [homeassistant.util.executor] Thread[SyncWorker_5] is still running at shutdown: File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 73, in download_calendar
    self._download_data()
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 159, in _download_data
    with CalendarData.opener_lock:
2023-03-17 14:20:00.739 WARNING (MainThread) [homeassistant.util.executor] Thread[SyncWorker_3] is still running at shutdown: File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 73, in download_calendar
    self._download_data()
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 159, in _download_data
    with CalendarData.opener_lock:
2023-03-17 14:20:00.878 WARNING (MainThread) [homeassistant.util.executor] Thread[SyncWorker_2] is still running at shutdown: File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 73, in download_calendar
    self._download_data()
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 159, in _download_data
    with CalendarData.opener_lock:
2023-03-17 14:20:01.016 WARNING (MainThread) [homeassistant.util.executor] Thread[SyncWorker_1] is still running at shutdown: File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 73, in download_calendar
    self._download_data()
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 162, in _download_data
    with urlopen(self._make_url()) as conn:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
2023-03-17 14:20:01.152 WARNING (MainThread) [homeassistant.util.executor] Thread[SyncWorker_6] is still running at shutdown: File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendar.py", line 205, in update
    self.data.update()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/homeassistant/util/__init__.py", line 192, in wrapper
    result = method(*args, **kwargs)
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendar.py", line 287, in update
    if self._calendar_data.download_calendar():
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 73, in download_calendar
    self._download_data()
  File "/Users/liuzhou/.homeassistant/custom_components/ics_calendar/calendardata.py", line 159, in _download_data
    with CalendarData.opener_lock:
2023-03-17 14:20:04.922 ERROR (MainThread) [root] Uncaught exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/hass", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/homeassistant/__main__.py", line 191, in main
    exit_code = runner.run(runtime_conf)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/homeassistant/runner.py", line 127, in run
    loop.close()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/unix_events.py", line 68, in close
    super().close()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/selector_events.py", line 88, in close
    super().close()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 677, in close
    executor.shutdown(wait=False)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/homeassistant/util/executor.py", line 68, in shutdown
    self.join_threads_or_timeout()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/homeassistant/util/executor.py", line 83, in join_threads_or_timeout
    remaining_threads -= join_or_interrupt_threads(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/homeassistant/util/executor.py", line 44, in join_or_interrupt_threads
    thread.join(timeout=timeout_per_thread)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1100, in join
    self._wait_for_tstate_lock(timeout=max(timeout, 0))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt
