2023-04-12 14:09:55.959 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration colorfulclouds which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-12 14:09:55.960 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration ics_calendar which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-12 14:09:55.961 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration xiaomi_miot_raw which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-12 14:09:55.962 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-12 14:10:03.696 WARNING (MainThread) [homeassistant.components.number] custom_components.xiaomi_miot_raw.number::MiotNumberInput is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.
2023-04-12 14:10:03.738 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] Timeout while loading MiCloud device list
2023-04-12 14:10:08.784 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-04-12 14:10:08.785 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-04-12 14:10:08.786 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-04-12 14:10:08.786 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-04-12 14:10:08.787 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-04-12 14:10:08.787 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-04-12 14:10:08.788 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-04-12 14:10:08.788 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-04-12 14:10:08.789 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-04-12 14:10:08.789 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-04-12 14:10:08.791 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-04-12 14:10:08.868 ERROR (MainThread) [homeassistant.config] Platform error: calendar
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/homeassistant/config.py", line 865, in async_process_component_config
    platform = p_integration.get_platform(domain)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/homeassistant/loader.py", line 728, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/homeassistant/loader.py", line 745, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/homeassistant/components/caldav/calendar.py", line 8, in <module>
    import caldav
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/caldav/__init__.py", line 3, in <module>
    from .davclient import DAVClient
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/caldav/davclient.py", line 15, in <module>
    from caldav.objects import Principal, Calendar, errmsg, log, ScheduleInbox, ScheduleOutbox
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/caldav/objects.py", line 9, in <module>
    import StringIO
ModuleNotFoundError: No module named 'StringIO'
2023-04-12 14:10:13.900 ERROR (MainThread) [homeassistant.components.climate] Platform xiaomi_miot_raw does not generate unique IDs. ID miotir-cloud-190208 is already used by climate.miotir_cloud_190208 - ignoring xiaomi_miot_raw.miotir-cloud-190208
2023-04-12 14:10:13.997 WARNING (MainThread) [homeassistant.components.media_player] Setup of media_player platform xiaomi_miot_raw is taking over 10 seconds.
2023-04-12 14:10:14.005 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] Error while requesting MIoT api /miotspec/prop/get : 
2023-04-12 14:10:19.027 WARNING (MainThread) [homeassistant.components.binary_sensor] Setup of binary_sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-04-12 14:10:19.028 WARNING (MainThread) [homeassistant.components.binary_sensor] Setup of binary_sensor platform xiaomi_miot_raw is taking over 10 seconds.
2023-04-12 14:10:19.028 WARNING (MainThread) [homeassistant.components.number] Setup of number platform xiaomi_miot_raw is taking over 10 seconds.
2023-04-12 14:10:19.029 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-04-12 14:10:19.029 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-04-12 14:10:19.030 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-04-12 14:10:19.030 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-04-12 14:10:19.031 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-04-12 14:10:19.031 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-04-12 14:10:19.032 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-04-12 14:10:19.033 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-04-12 14:10:19.034 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-04-12 14:10:19.034 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-04-12 14:10:19.034 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-04-12 14:10:19.035 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-04-12 14:10:19.035 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-04-12 14:10:19.035 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-04-12 14:10:19.036 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-04-12 14:10:19.037 WARNING (MainThread) [homeassistant.components.fan] Setup of fan platform xiaomi_miot_raw is taking over 10 seconds.
2023-04-12 14:10:19.038 WARNING (MainThread) [homeassistant.components.fan] Setup of fan platform xiaomi_miot_raw is taking over 10 seconds.
2023-04-12 14:10:19.039 WARNING (MainThread) [homeassistant.components.fan] Setup of fan platform xiaomi_miot_raw is taking over 10 seconds.
2023-04-12 14:10:19.039 WARNING (MainThread) [homeassistant.components.cover] Setup of cover platform xiaomi_miot_raw is taking over 10 seconds.
2023-04-12 14:10:19.044 ERROR (MainThread) [custom_components.xiaomi_miot_raw.deps.xiaomi_cloud_new] Error while requesting MIoT api /miotspec/prop/get : 
2023-04-12 14:10:19.332 ERROR (MainThread) [custom_components.xiaomi_miot_raw] Can't login to MiCloud
2023-04-12 14:10:19.335 WARNING (MainThread) [homeassistant.config_entries] Config entry '1875***0567' for xiaomi_miot_raw integration not ready yet: None; Retrying in background
2023-04-12 14:10:19.339 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/Users/liuzhou/.homeassistant/custom_components/xiaomi_miot_raw/basic_dev_class.py", line 554, in create_sub_entities
    self._hass.data[DOMAIN]['add_handler']['number'][self._entry_id](num_to_add, update_before_add=True)
KeyError: 'number'
2023-04-12 14:10:43.048 ERROR (MainThread) [custom_components.xiaomi_miot_raw] The main device of 小米无线开关(255.255.255.255) is still not ready after 30 seconds!
2023-04-12 14:10:43.050 WARNING (MainThread) [homeassistant.components.select] Platform xiaomi_miot_raw not ready yet: None; Retrying in background in 30 seconds
2023-04-12 14:10:44.758 ERROR (SyncWorker_4) [homeassistant] Error doing job: Unclosed client session
2023-04-12 14:10:48.920 WARNING (SyncWorker_4) [scapy.runtime] No IPv4 address found on en5 !
2023-04-12 14:10:48.946 WARNING (SyncWorker_4) [scapy.runtime] No IPv4 address found on ap1 !
2023-04-12 14:10:48.996 WARNING (SyncWorker_4) [scapy.runtime] more No IPv4 address found on awdl0 !
2023-04-12 14:10:53.089 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
2023-04-12 14:11:13.363 ERROR (MainThread) [custom_components.xiaomi_miot_raw] The main device of 小米无线开关(255.255.255.255) is still not ready after 30 seconds!
2023-04-12 14:11:31.273 ERROR (MainThread) [frontend.js.latest.202211021] blob:http://127.0.0.1:8123/aeaf86ca-59dc-46d5-9dc1-60b12827d724:1:1 Uncaught SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
2023-04-12 14:11:31.618 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 336, in _async_on_data
    await self._async_send_response_rootdevice(remote_addr)
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 401, in _async_send_response_rootdevice
    await self._async_send_response(
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 469, in _async_send_response
    self._response_socket.sendto(packet, remote_addr)
OSError: [Errno 65] No route to host
2023-04-12 14:11:34.997 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 336, in _async_on_data
    await self._async_send_response_rootdevice(remote_addr)
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 401, in _async_send_response_rootdevice
    await self._async_send_response(
  File "/Users/liuzhou/.homeassistant/deps/lib/python/site-packages/async_upnp_client/server.py", line 469, in _async_send_response
    self._response_socket.sendto(packet, remote_addr)
OSError: [Errno 65] No route to host
2023-04-12 14:12:23.366 WARNING (MainThread) [homeassistant.components.select] Setup of select platform xiaomi_miot_raw is taking over 10 seconds.
